export const profiles = {
  'rule-maker':           { id:'rule-maker',           name:'Rule Maker',           emoji:'👑', color:'#00ACC1', bgColor:'#E0F7FA', plotX:85, plotY:85, tagline:'Experienced innovation thought leader', description:'You skillfully and courageously challenge the status quo and execute powerful value propositions for today and the future. You are a rare combination of strategic vision and execution excellence.', strengths:['Strategic innovation leadership','Cross-functional execution','Ecosystem orchestration','Value proposition design'], drivers:['Purpose-driven innovation','Complex challenge appetite','Executive influence'], enablers:['Strong network','Proven track record','Executive sponsorship'], barriers:['Risk of over-engineering','Difficulty delegating','Scaling innovation culture'], suggestions:['Lead innovation transformation programmes','Mentor Rule Challengers and Rule Breakers','Build ISO 56002 aligned innovation systems'], gimiLevel:'Level 3–4: Innovation Leadership', certification:'CCIO (Certified Chief Innovation Officer)', investment:'$1,999–$3,999/month' },
  'rule-breaker':         { id:'rule-breaker',         name:'Rule Breaker',         emoji:'⚡', color:'#7C3AED', bgColor:'#F5F3FF', plotX:50, plotY:85, tagline:'Creative experimenter who continuously pivots', description:'You are a creative, forward-thinking learner and experimenter who continuously pivots to build the new. Your energy and creativity are your superpowers — your next step is channelling them with structure.', strengths:['Creative ideation','Rapid experimentation','Learning agility','Disruptive thinking'], drivers:['Curiosity and exploration','Freedom to experiment','Recognition of ideas'], enablers:['Supportive environment','Access to diverse collaborators','Tolerance for failure'], barriers:['Execution consistency','Framework knowledge gaps','Portfolio discipline'], suggestions:['Master 2–3 core innovation frameworks','Partner with Rule Executors for delivery','Develop portfolio management skills'], gimiLevel:'Level 2: Innovation Management Master', certification:'CIP (Certified Innovation Professional) Master', investment:'$899–$1,099/month' },
  'rule-challenger':      { id:'rule-challenger',      name:'Rule Challenger',      emoji:'🚀', color:'#059669', bgColor:'#ECFDF5', plotX:15, plotY:85, tagline:'Creative A-Player eager to build the new', description:'You have the right attitude to learn by doing with an eagerness to build the new. Your innovation mindset is your greatest asset — pairing it with the right tools will make you unstoppable.', strengths:['Strong innovation mindset','Entrepreneurial energy','Courage to challenge norms','Learning eagerness'], drivers:['Autonomy and ownership','Purpose-driven challenges','Learning opportunities'], enablers:['Access to mentors','Safe space to experiment','Cross-functional exposure'], barriers:['Limited toolkit','Lack of structured methodology','Execution gaps'], suggestions:['Start with CIP Associate to build your toolkit','Apply Design Thinking on a real project','Find a Rule Maker mentor'], gimiLevel:'Level 1: Innovation Management Proficient', certification:'CIP (Certified Innovation Professional) Associate', investment:'$499–$699/month' },
  'diamond-in-the-rough': { id:'diamond-in-the-rough', name:'Diamond in the Rough', emoji:'💎', color:'#D97706', bgColor:'#FFFBEB', plotX:25, plotY:50, tagline:'Sharp thinker with strong untapped potential', description:'You are open to learning and have strong foundations to foster your innovation potential. With the right development path, you have the raw material to become an exceptional innovator.', strengths:['Analytical thinking','Openness to growth','Solid intellectual foundations','Genuine potential'], drivers:['Personal development opportunities','Clear growth path','Tangible impact'], enablers:['Structured learning','Supportive team','Recognition of potential'], barriers:['Mindset development needed','Limited innovation exposure','Confidence building'], suggestions:['Start with IMI to identify key development areas','Join cross-functional innovation projects','Build your innovation vocabulary'], gimiLevel:'Level 1: Innovation Management Proficient', certification:'IMI (Innovation Mindset Index) + CIP Associate', investment:'$99 + $499/month' },
  'optimistic-executor':  { id:'optimistic-executor',  name:'Optimistic Executor',  emoji:'⚙️', color:'#2563EB', bgColor:'#EFF6FF', plotX:75, plotY:50, tagline:'Result-driven executor with disciplined flexibility', description:'You bring together ideas in a fast, flexible and disciplined approach. You are the engine that turns innovation into reality — your next step is building stronger creative vision.', strengths:['Execution excellence','Results orientation','Operational discipline','Cross-team coordination'], drivers:['Clear goals and milestones','Visible impact','Team collaboration'], enablers:['Structured processes','Clear accountability','Resources and authority'], barriers:['Strategic creative thinking','Ambiguity tolerance','Long-term visioning'], suggestions:['Develop creative thinking through Design Sprints','Partner with Rule Breakers for ideation','Practice Horizon 2/3 planning exercises'], gimiLevel:'Level 2: Innovation Management Master', certification:'CIP Master + Strategic Thinking module', investment:'$699–$899/month' },
  'rule-executor':        { id:'rule-executor',        name:'Rule Executor',        emoji:'📋', color:'#DC2626', bgColor:'#FEF2F2', plotX:78, plotY:17, tagline:'Domain expert who delivers when the path is clear', description:'You bring specific know-how to innovation teams and must see short-term results to gain confidence to invest time in building the new. Your expertise is invaluable — your journey is to trust ambiguity.', strengths:['Deep technical expertise','Process discipline','Reliable delivery','Knowledge depth'], drivers:['Short-term wins','Visible ROI','Domain recognition'], enablers:['Clear deliverables','Defined processes','Measured outcomes'], barriers:['Growth mindset development','Risk tolerance','Creative experimentation'], suggestions:['Start with IMI to map your development journey','Participate in low-risk innovation pilots','Partner with Rule Challengers for new thinking styles'], gimiLevel:'Level 1: Innovation Management Proficient', certification:'IMI (Innovation Mindset Index) + CIP Associate', investment:'$99 + $499/month' },
  'rule-follower':        { id:'rule-follower',        name:'Rule Follower',        emoji:'📌', color:'#6B7280', bgColor:'#F9FAFB', plotX:20, plotY:17, tagline:'Reliable professional who excels within structure', description:'You accept established practices and prefer to follow rules and guidelines to execute activities. Your reliability and consistency are genuine strengths — and innovation can be learned.', strengths:['Process adherence','Reliability','Risk management','Operational stability'], drivers:['Stability and predictability','Clear authority and direction','Incremental improvement'], enablers:['Structured environment','Clear expectations','Peer support'], barriers:['Innovation mindset','Tolerance for ambiguity','Creative thinking'], suggestions:['Begin with IMI to understand your starting point','Explore incremental innovation within your current role','Attend GIMI introductory workshops'], gimiLevel:'Level 1: Innovation Management Proficient (Entry)', certification:'IMI (Innovation Mindset Index)', investment:'$99 (start here)' },
};

export function determineProfile(m, k) {
  if (m >= 67) { if (k >= 67) return profiles['rule-maker']; if (k >= 34) return profiles['rule-breaker']; return profiles['rule-challenger']; }
  if (m >= 34) { if (k >= 51) return profiles['optimistic-executor']; return profiles['diamond-in-the-rough']; }
  if (k >= 51) return profiles['rule-executor'];
  return profiles['rule-follower'];
}

export const allProfiles = Object.values(profiles);
