// All scoring runs on the frontend so the app works standalone on GitHub Pages

export const questions = [
  { id:1,  category:'mindset',    sub:'growthMindset',         text:'When you encounter a significant setback on an innovation project, what is your typical reaction?', options:[{t:'I see it as valuable learning and immediately adjust my approach',s:5},{t:'I analyse what went wrong and try a different way',s:4},{t:'I feel frustrated but eventually move forward',s:3},{t:'I question whether the project is worth continuing',s:2},{t:'I conclude the approach will not work and move on',s:1}] },
  { id:2,  category:'mindset',    sub:'growthMindset',         text:'How do you respond to feedback that challenges your ideas?', options:[{t:'I actively seek critical feedback and use it to improve',s:5},{t:'I welcome it and usually incorporate useful points',s:4},{t:'I listen but sometimes struggle to act on criticism',s:3},{t:'I find it difficult to separate feedback from personal criticism',s:2},{t:'I prefer to proceed with my original idea',s:1}] },
  { id:3,  category:'mindset',    sub:'grit',                  text:'How do you maintain focus on long-term innovation goals when short-term pressures arise?', options:[{t:'I consistently prioritise long-term goals despite short-term distractions',s:5},{t:'I usually stay focused but sometimes get pulled into immediate needs',s:4},{t:'I balance both, sometimes losing sight of either',s:3},{t:'Short-term pressures frequently override my innovation goals',s:2},{t:'I primarily focus on immediate deliverables',s:1}] },
  { id:4,  category:'mindset',    sub:'grit',                  text:'When an innovation initiative faces repeated obstacles, what do you do?', options:[{t:'I persist and find creative solutions regardless of how many obstacles arise',s:5},{t:'I persevere through most obstacles with occasional pivots',s:4},{t:'I continue but sometimes need external motivation to push through',s:3},{t:'I look for reasons to pivot or stop if obstacles are significant',s:2},{t:'I escalate or abandon when obstacles become too frequent',s:1}] },
  { id:5,  category:'mindset',    sub:'creativeCollaboration', text:'How do you approach co-creating ideas with people from very different backgrounds?', options:[{t:'I thrive on diverse perspectives and actively build on different viewpoints',s:5},{t:'I appreciate diversity and usually find it energising',s:4},{t:'I work well with diverse teams but prefer familiar collaborators',s:3},{t:'I find it challenging to align across very different perspectives',s:2},{t:'I prefer working with people who share my background and approach',s:1}] },
  { id:6,  category:'mindset',    sub:'creativeCollaboration', text:'In a brainstorming session, what role do you naturally take?', options:[{t:"I actively build on others' ideas while generating many of my own",s:5},{t:"I contribute ideas and help expand on others' concepts",s:4},{t:'I participate but tend to be selective about contributing',s:3},{t:'I mostly evaluate ideas rather than generate new ones',s:2},{t:'I prefer structured problem-solving over open brainstorming',s:1}] },
  { id:7,  category:'mindset',    sub:'flexibleExecution',     text:'When you discover mid-project that your initial approach is not working, what do you do?', options:[{t:'I pivot quickly and restructure the entire approach if needed',s:5},{t:'I adjust the approach while maintaining core project goals',s:4},{t:'I make incremental adjustments and monitor results',s:3},{t:'I prefer to exhaust the current approach before considering changes',s:2},{t:'I wait for direction before changing course',s:1}] },
  { id:8,  category:'mindset',    sub:'flexibleExecution',     text:'How comfortable are you with ambiguity and undefined processes in innovation work?', options:[{t:'I am energised by ambiguity and create structure as needed',s:5},{t:'I am comfortable with ambiguity and operate effectively within it',s:4},{t:'I can manage ambiguity but prefer some defined structure',s:3},{t:'Ambiguity slows my progress and makes me uncomfortable',s:2},{t:'I require clear processes and defined outcomes to work effectively',s:1}] },
  { id:9,  category:'knowledge',  sub:'intent',                text:'How clearly can you articulate the strategic purpose of innovation within your organisation?', options:[{t:'I clearly connect innovation initiatives to business strategy and value creation',s:5},{t:'I understand our innovation direction and can explain it to others',s:4},{t:'I have a general sense of our goals but not the full strategic picture',s:3},{t:'I focus on my role without full visibility into innovation strategy',s:2},{t:'Innovation strategy is not clearly defined or communicated where I work',s:1}] },
  { id:10, category:'knowledge',  sub:'intent',                text:'How do you define success for an innovation initiative before starting?', options:[{t:'I establish clear metrics tied to strategic outcomes and customer value',s:5},{t:'I define success criteria balancing business impact and learning',s:4},{t:'I set general goals but refine metrics as the project progresses',s:3},{t:'I rely on qualitative feedback to evaluate success',s:2},{t:'Success is determined by leadership after the fact',s:1}] },
  { id:11, category:'knowledge',  sub:'concepts',              text:'How familiar are you with structured innovation frameworks (Design Thinking, Jobs-to-be-Done, Stage-Gate)?', options:[{t:'I apply multiple frameworks fluidly and adapt them to context',s:5},{t:'I am proficient in 2–3 frameworks and know when to apply them',s:4},{t:'I am familiar with frameworks but apply them inconsistently',s:3},{t:'I have basic awareness but limited practical application',s:2},{t:'I am not familiar with formal innovation frameworks',s:1}] },
  { id:12, category:'knowledge',  sub:'concepts',              text:'How do you identify and validate innovation opportunities before investing resources?', options:[{t:'I use systematic research: market analysis, user research, competitive intelligence',s:5},{t:'I conduct targeted user research and market analysis for key decisions',s:4},{t:'I gather some qualitative feedback before proceeding',s:3},{t:'I rely primarily on internal observations and team input',s:2},{t:'I proceed based on intuition or executive direction',s:1}] },
  { id:13, category:'knowledge',  sub:'resources',             text:'How effectively do you access and deploy resources (people, budget, tools) for innovation?', options:[{t:'I have strong networks and proven methods to secure and deploy resources quickly',s:5},{t:'I can usually access needed resources and manage them well',s:4},{t:'I access resources but sometimes face delays or limitations',s:3},{t:'Resource access is a frequent challenge that slows my work',s:2},{t:'Limited resources significantly constrain my ability to innovate',s:1}] },
  { id:14, category:'knowledge',  sub:'resources',             text:'How do you leverage external partnerships, startups, or ecosystems for innovation?', options:[{t:'I systematically identify and integrate external partners into our innovation pipeline',s:5},{t:'I actively seek external partnerships and have established key relationships',s:4},{t:'I engage external partners occasionally when the opportunity arises',s:3},{t:'I am aware of the value but have not established meaningful partnerships',s:2},{t:'We primarily rely on internal capabilities for innovation',s:1}] },
  { id:15, category:'knowledge',  sub:'makeItReal',            text:'How do you move innovation concepts from idea to tested prototype or pilot?', options:[{t:'I run rapid experiments with clear learning goals and scale what works',s:5},{t:'I build MVPs and test with real users before full investment',s:4},{t:'I develop prototypes but user testing is inconsistent',s:3},{t:'I tend to develop more comprehensive solutions before testing',s:2},{t:'Most ideas remain as concepts without structured implementation',s:1}] },
  { id:16, category:'knowledge',  sub:'makeItReal',            text:'How do you measure and communicate the impact of innovation initiatives?', options:[{t:'I track KPIs throughout the innovation lifecycle and report impact clearly',s:5},{t:'I measure outcomes at key milestones and share results with stakeholders',s:4},{t:'I measure success at the end of projects but not consistently throughout',s:3},{t:'Measurement is informal and primarily based on stakeholder feedback',s:2},{t:'Impact measurement is not a structured part of my innovation work',s:1}] },
];

const subLabels = { growthMindset:'Growth Mindset', grit:'Grit', creativeCollaboration:'Creative Collaboration', flexibleExecution:'Flexible Execution', intent:'Intent', concepts:'Concepts', resources:'Resources', makeItReal:'Make it Real' };

export function scoreAnswers(answers) {
  const subs = { growthMindset:[], grit:[], creativeCollaboration:[], flexibleExecution:[], intent:[], concepts:[], resources:[], makeItReal:[] };
  answers.forEach(({ questionId, optionIndex }) => {
    const q = questions.find(q => q.id === questionId);
    if (!q) return;
    subs[q.sub].push(q.options[optionIndex]?.s ?? 1);
  });
  const avg = arr => arr.length ? arr.reduce((a,b)=>a+b,0)/arr.length : 1;
  const toPct = arr => Math.round(((avg(arr)-1)/4)*100);
  const mindsetSubs = { growthMindset:toPct(subs.growthMindset), grit:toPct(subs.grit), creativeCollaboration:toPct(subs.creativeCollaboration), flexibleExecution:toPct(subs.flexibleExecution) };
  const ktSubs = { intent:toPct(subs.intent), concepts:toPct(subs.concepts), resources:toPct(subs.resources), makeItReal:toPct(subs.makeItReal) };
  const mindsetScore = Math.round(Object.values(mindsetSubs).reduce((a,b)=>a+b,0)/4);
  const ktScore = Math.round(Object.values(ktSubs).reduce((a,b)=>a+b,0)/4);
  return { mindsetScore, ktScore, mindsetSubs, ktSubs };
}

export function classifySubs(subs) {
  return Object.entries(subs).map(([key, score]) => ({ key, label: subLabels[key], score, role: score>=70?'driver':score>=40?'enabler':'barrier' }));
}
